# Generated by Django 5.0.4 on 2024-04-20 16:29

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_is_published_user_time_create_user_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tid',
            field=api.models.HashField(max_length=64, null=True),
        ),
    ]
