# Generated by Django 5.0.4 on 2024-04-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='meat.jpeg'),
        ),
        migrations.AddField(
            model_name='item',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
